parameters:
    token: '%env(JWT_SECRET)%'

services:
    App\Service\JwtManager:
        arguments:
            $secret: '%token%'
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
