parameters:
    token_secret: '%env(JWT_SECRET)%'
    images_directory: '%kernel.project_dir%/public/uploads/img_produits'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
